name: appistery
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  dio: ^5.7.0
  easy_localization: ^3.0.7
  flutter_secure_storage: ^9.2.2
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.3.3
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  timeago: ^3.7.0
  webview_flutter: ^4.10.0
  url_launcher: ^6.3.1
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.5
  connectivity_plus: ^6.1.1
  image_picker: ^1.1.2
  file_picker: ^8.1.4
  flutter_image_compress: ^2.3.0
  path_provider: ^2.1.5
  flutter_dotenv: ^6.0.0
  device_info_plus: ^10.1.0
  http: ^1.2.1
  socket_io_client: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo-appistery-no.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/logo/
    - assets/onboarding/
    - .env
